import { OfferData } from '../domain/model/offer';

export function createDemoOffers(now: number): OfferData[] {
  const pickupStartAt = new Date(now - 15 * 60 * 1000).toISOString();
  const laterPickupStartAt = new Date(now + 30 * 60 * 1000).toISOString();
  const pickupEndAt = new Date(now + 24 * 60 * 60 * 1000).toISOString();

  return [
    {
      id: 1,
      businessId: 1,
      category: 'meals',
      title: 'Almuerzo limeño',
      description: 'Arroz, pollo a la parrilla y verduras preparados hoy.',
      allergens: 'Leche',
      originalPrice: 32,
      offerPrice: 16,
      initialUnits: 8,
      availableUnits: 8,
      pickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/pollo-arroz.png',
    },
    {
      id: 2,
      businessId: 2,
      category: 'bakery',
      title: 'Bolsa de panadería',
      description: 'Una selección de panes y productos de panadería de hoy.',
      allergens: 'Gluten, huevos, leche',
      originalPrice: 24,
      offerPrice: 10,
      initialUnits: 5,
      availableUnits: 5,
      pickupStartAt: laterPickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/panaderia.png',
    },
    {
      id: 3,
      businessId: 4,
      category: 'vegetarian',
      title: 'Bowl de la huerta',
      description: 'Verduras de temporada, quinua y aliño de la casa.',
      allergens: 'Frutos secos',
      originalPrice: 28,
      offerPrice: 14,
      initialUnits: 4,
      availableUnits: 4,
      pickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/bowl-vegetariano.png',
    },
    {
      id: 4,
      businessId: 3,
      category: 'meals',
      title: 'Almuerzo tradicional',
      description: 'Una porción generosa de almuerzo casero peruano.',
      allergens: 'Consulta al restaurante',
      originalPrice: 30,
      offerPrice: 15,
      initialUnits: 6,
      availableUnits: 6,
      pickupStartAt: laterPickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/almuerzo-criollo.png',
    },
    {
      id: 5,
      businessId: 2,
      category: 'desserts',
      title: 'Caja de postre',
      description: 'Dos postres seleccionados de la vitrina de hoy.',
      allergens: 'Gluten, huevos, leche',
      originalPrice: 22,
      offerPrice: 9,
      initialUnits: 3,
      availableUnits: 3,
      pickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/caja-postres.png',
    },
    {
      id: 6,
      businessId: 1,
      category: 'vegetarian',
      title: 'Plato de verduras al horno',
      description: 'Verduras recién horneadas con arroz y hierbas.',
      allergens: 'Ninguno declarado; consulta sobre el contacto cruzado',
      originalPrice: 26,
      offerPrice: 12,
      initialUnits: 7,
      availableUnits: 7,
      pickupStartAt: laterPickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/arroz-verduras.png',
    },
    {
      id: 8,
      businessId: 1,
      category: 'desserts',
      title: 'Postre de la casa',
      description: 'Un postre del día; consulta la disponibilidad con el equipo.',
      allergens: 'Leche, huevos',
      originalPrice: 18,
      offerPrice: 8,
      initialUnits: 1,
      availableUnits: 0,
      pickupStartAt: laterPickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '',
    },
    {
      id: 9,
      businessId: 1,
      plusExclusive: true,
      category: 'meals',
      title: 'Menú especial de la casa',
      description:
        'Selección especial de la cocina con plato principal, guarnición y postre del día. Exclusiva para clientes foodSavePlus.',
      allergens: 'Leche, huevos',
      originalPrice: 48,
      offerPrice: 24,
      initialUnits: 4,
      availableUnits: 4,
      pickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/pollo-arroz.png',
    },
    {
      id: 10,
      businessId: 4,
      plusExclusive: true,
      category: 'vegetarian',
      title: 'Bowl especial de temporada',
      description:
        'Selección de quinua, verduras de temporada y complementos de la casa. Exclusiva para clientes foodSavePlus.',
      allergens: 'Frutos secos',
      originalPrice: 40,
      offerPrice: 20,
      initialUnits: 3,
      availableUnits: 3,
      pickupStartAt: laterPickupStartAt,
      pickupEndAt,
      expiresAt: pickupEndAt,
      status: 'ACTIVE',
      image: '/assets/bowl-vegetariano.png',
    },
  ];
}
